/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sewapcapp;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Zaidan
 */
public class FormSignUp extends javax.swing.JFrame {

        Connection Connector = null;
        ResultSet rs = null;
        PreparedStatement pst = null;
        Statement statSignUp ;
        String sql;
        int xx, yy ;//untuk drag aplikasi
        
        private void ConnectorSignUp(){
            try{
                Class.forName("com.mysql.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/sewa_pc";
                String usr = "root";
                String pass = "";
                Connector = (Connection) DriverManager.getConnection(url,usr,pass);
                statSignUp = (Statement) Connector.createStatement(rs.TYPE_SCROLL_SENSITIVE,rs.CONCUR_UPDATABLE);
                rs = statSignUp.executeQuery("select * from login_sewa_pc");
                
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                System.exit(0);
            }
        
        
        }
        
        private void Clear(){
        field_nama.setText(null);
        field_username.setText(null);
        field_pass.setText(null);
        field_repass.setText(null);
    }
        
        public void Check(){
        String registerPassword = new String (field_pass.getPassword());
        String rePassword = new String (field_repass.getPassword());
        
            if (registerPassword.equals(rePassword)){
                checkerPass.setText("Password sama");
            }else if (!registerPassword.equals(rePassword)){
                checkerPass.setText("Password tidak sama!");
            } 
        }
        
       
       
    public FormSignUp() {
        initComponents();
        Dimension screenSize=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension display=Toolkit.getDefaultToolkit().getScreenSize();
        
        int x = display.width / 2 - this.getSize().width /2;
        int y = display.height/ 2 - this.getSize().width /2;
        
        this.setLocation(x,y);
        checkerPass.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jendela = new com.k33ptoo.components.KGradientPanel();
        btn_exit = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JLabel();
        field_nama = new javax.swing.JTextField();
        txt_user = new javax.swing.JLabel();
        field_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JLabel();
        field_pass = new javax.swing.JPasswordField();
        txt_repass = new javax.swing.JLabel();
        field_repass = new javax.swing.JPasswordField();
        checkerPass = new javax.swing.JLabel();
        btn_reg = new com.k33ptoo.components.KButton();
        btn_back = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jendela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jendela.setkEndColor(new java.awt.Color(67, 206, 255));
        jendela.setkGradientFocus(1000);
        jendela.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/reject(20x20).png"))); // NOI18N
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });
        jendela.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jendela.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(67, 206, 255));
        jLabel10.setText("SIGN UP");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        txt_nama.setFont(new java.awt.Font("Dubai", 1, 11)); // NOI18N
        txt_nama.setForeground(new java.awt.Color(67, 206, 255));
        txt_nama.setText("Nama");
        jPanel2.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        field_nama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(67, 206, 255)));
        field_nama.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        field_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_namaActionPerformed(evt);
            }
        });
        jPanel2.add(field_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 210, -1));

        txt_user.setFont(new java.awt.Font("Dubai", 1, 11)); // NOI18N
        txt_user.setForeground(new java.awt.Color(67, 206, 255));
        txt_user.setText("Username");
        jPanel2.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        field_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(67, 206, 255)));
        field_username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(field_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 210, -1));

        txt_password.setFont(new java.awt.Font("Dubai", 1, 11)); // NOI18N
        txt_password.setForeground(new java.awt.Color(67, 206, 255));
        txt_password.setText("Password");
        jPanel2.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        field_pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(67, 206, 255)));
        field_pass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        field_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_passActionPerformed(evt);
            }
        });
        jPanel2.add(field_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 210, -1));

        txt_repass.setFont(new java.awt.Font("Dubai", 1, 11)); // NOI18N
        txt_repass.setForeground(new java.awt.Color(67, 206, 255));
        txt_repass.setText("Re-Password");
        jPanel2.add(txt_repass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        field_repass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(67, 206, 255)));
        field_repass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        field_repass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_repassActionPerformed(evt);
            }
        });
        field_repass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                field_repassKeyReleased(evt);
            }
        });
        jPanel2.add(field_repass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 210, -1));

        checkerPass.setFont(new java.awt.Font("Dubai", 3, 11)); // NOI18N
        checkerPass.setForeground(new java.awt.Color(67, 206, 255));
        checkerPass.setText("check");
        jPanel2.add(checkerPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 210, -1));

        btn_reg.setText("REGISTER");
        btn_reg.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_reg.setkEndColor(new java.awt.Color(67, 206, 255));
        btn_reg.setkHoverEndColor(new java.awt.Color(67, 206, 255));
        btn_reg.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg.setkSelectedColor(new java.awt.Color(255, 255, 255));
        btn_reg.setkStartColor(new java.awt.Color(225, 0, 225));
        btn_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regActionPerformed(evt);
            }
        });
        jPanel2.add(btn_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 210, 30));

        btn_back.setBackground(new java.awt.Color(255, 255, 255));
        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_backMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 228, 255));
        jLabel2.setText("Log In");
        btn_back.add(jLabel2);

        jPanel2.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 60, 30));

        jendela.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 270, 400));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/logo2.png"))); // NOI18N
        jLabel1.setText("ZDN COMP");
        jendela.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("<ZDN BOT./>");
        jendela.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, 20));

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hi....");
        jendela.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 70, -1));

        jLabel7.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SILAHKAN UNTUK");
        jendela.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MELAKUKAN REGISTRASI");
        jendela.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        getContentPane().add(jendela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void field_repassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_repassKeyReleased
        Check();
    }//GEN-LAST:event_field_repassKeyReleased

    private void field_repassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_repassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_repassActionPerformed

    private void field_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_passActionPerformed

    private void field_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_namaActionPerformed

    }//GEN-LAST:event_field_namaActionPerformed

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        dispose();
    }//GEN-LAST:event_btn_exitMousePressed

    private void btn_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regActionPerformed
        
        String nama = field_nama.getText();
        String username = field_username.getText();
        String password = new String(field_pass.getPassword());
        String Confirm_pass = new String(field_pass.getPassword());
        
        

        try {
            ConnectorSignUp();
            pst = (PreparedStatement) Connector.prepareStatement("INSERT INTO login_sewa_pc (nama,username,password,Confirm_pass)VALUES(?,?,?,?)");
            pst.setString(1, nama);
            pst.setString(2, username);
            pst.setString(3, password);
            pst.setString(4, Confirm_pass);

            int k = pst.executeUpdate();

            if(k==1){
                JOptionPane.showMessageDialog(this, "Kamu berhasil meregistrasi");
                field_nama.setText("");
                field_username.setText("");
                field_pass.setText("");
            }else{
                JOptionPane.showMessageDialog(this, "Gagal meregistrasi");
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormSignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
                                   
    }//GEN-LAST:event_btn_regActionPerformed

    private void btn_backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMousePressed
        new FormSignIn().setVisible(true); 
        this.setVisible(false);
        
    }//GEN-LAST:event_btn_backMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_back;
    private javax.swing.JLabel btn_exit;
    private com.k33ptoo.components.KButton btn_reg;
    private javax.swing.JLabel checkerPass;
    private javax.swing.JTextField field_nama;
    private javax.swing.JPasswordField field_pass;
    private javax.swing.JPasswordField field_repass;
    private javax.swing.JTextField field_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.k33ptoo.components.KGradientPanel jendela;
    private javax.swing.JLabel txt_nama;
    private javax.swing.JLabel txt_password;
    private javax.swing.JLabel txt_repass;
    private javax.swing.JLabel txt_user;
    // End of variables declaration//GEN-END:variables

    private String field_repassKeyReleased(ActionEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
