/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sewapcapp;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.File;
import java.io.InputStream;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;



/**
 *
 * @author Zaidan
 */
public class FormAdmin extends javax.swing.JFrame {

    Connection connector = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement statSewa ;
    String sql;
    int xx,yy;
    private String ReportPath="report/";

    
    
    private void Connector(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://localhost/sewa_pc"; //url database
            String user="root"; //user database
            String pass=""; //password database
            connector = (Connection) DriverManager.getConnection(url,user,pass);
            statSewa = (Statement) connector.createStatement(rs.TYPE_SCROLL_SENSITIVE,rs.CONCUR_UPDATABLE);
            rs = statSewa.executeQuery("select * from sewa_pc_table");
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                System.exit(0);
            }
    }
    
    //class Display
    private void display(){
        try{
            sql="select * from sewa_pc_table";
            pst = (PreparedStatement) connector.prepareStatement(sql);
            rs = pst.executeQuery();
            table_database.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    //class clear
    private void Clear(){
        field_userid.setText(null);
        field_nama.setText(null);
        field_waktu.setText(null);
        field_harga.setText(null);
    }    
    
    public FormAdmin() {
        initComponents();
        Connector();
        display();
        
        Dimension screenSize=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension display=Toolkit.getDefaultToolkit().getScreenSize();
        
        int x = display.width / 2 - this.getSize().width /2;
        int y = display.height/ 2 - this.getSize().width /2;
        
        this.setLocation(x,y);
        
        //table
//        table_database.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
//        table_database.getTableHeader().setOpaque(false);
//        table_database.getTableHeader().setBackground(new Color(32, 136, 203));
//        table_database.getTableHeader().setForeground(new Color(102, 102, 102));
//        table_database.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("sewa_pc?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        sewaPcTableQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT s FROM SewaPcTable s");
        sewaPcTableList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : sewaPcTableQuery.getResultList();
        kGradientPanel11 = new com.k33ptoo.components.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        userid = new javax.swing.JLabel();
        field_userid = new javax.swing.JTextField();
        field_nama = new javax.swing.JTextField();
        nama = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();
        field_waktu = new javax.swing.JTextField();
        harga = new javax.swing.JLabel();
        field_harga = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        kButton1 = new com.k33ptoo.components.KButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_database = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kGradientPanel11.setkEndColor(new java.awt.Color(67, 206, 255));
        kGradientPanel11.setkGradientFocus(1000);
        kGradientPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/logo2.png"))); // NOI18N
        jLabel2.setText("ZDN COMP");
        kGradientPanel11.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DASHBOARD ADMIN");
        kGradientPanel11.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        userid.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        userid.setForeground(new java.awt.Color(255, 255, 255));
        userid.setText("ID");
        kGradientPanel11.add(userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 48, -1));

        field_userid.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        field_userid.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        field_userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_useridActionPerformed(evt);
            }
        });
        kGradientPanel11.add(field_userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 260, -1));

        field_nama.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        field_nama.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kGradientPanel11.add(field_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 260, -1));

        nama.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setText("Nama");
        kGradientPanel11.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        waktu.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        waktu.setForeground(new java.awt.Color(255, 255, 255));
        waktu.setText("Waktu/Jam");
        kGradientPanel11.add(waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        field_waktu.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        field_waktu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        field_waktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_waktuActionPerformed(evt);
            }
        });
        kGradientPanel11.add(field_waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 260, -1));

        harga.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        harga.setForeground(new java.awt.Color(255, 255, 255));
        harga.setText("Harga");
        kGradientPanel11.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        field_harga.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        field_harga.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kGradientPanel11.add(field_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 260, -1));

        btn_simpan.setBackground(new java.awt.Color(255, 255, 255));
        btn_simpan.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btn_simpan.setForeground(new java.awt.Color(51, 51, 51));
        btn_simpan.setText("SIMPAN");
        btn_simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        kGradientPanel11.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        btn_edit.setBackground(new java.awt.Color(255, 255, 255));
        btn_edit.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(51, 51, 51));
        btn_edit.setText("EDIT");
        btn_edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        kGradientPanel11.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 70, -1));

        btn_hapus.setBackground(new java.awt.Color(255, 255, 255));
        btn_hapus.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(51, 51, 51));
        btn_hapus.setText("HAPUS");
        btn_hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        kGradientPanel11.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 70, -1));

        btn_clear.setBackground(new java.awt.Color(255, 255, 255));
        btn_clear.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(51, 51, 51));
        btn_clear.setText("CLEAR");
        btn_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        kGradientPanel11.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 70, -1));

        btn_keluar.setBackground(new java.awt.Color(255, 255, 255));
        btn_keluar.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btn_keluar.setForeground(new java.awt.Color(51, 51, 51));
        btn_keluar.setText("KELUAR");
        btn_keluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });
        kGradientPanel11.add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 70, -1));

        kButton1.setBorder(null);
        kButton1.setText("PRINT");
        kButton1.setFont(new java.awt.Font("Dubai Medium", 1, 10)); // NOI18N
        kButton1.setkBackGroundColor(new java.awt.Color(225, 0, 225));
        kButton1.setkBorderRadius(5);
        kButton1.setkEndColor(new java.awt.Color(67, 206, 255));
        kButton1.setkHoverEndColor(new java.awt.Color(67, 206, 255));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton1.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton1.setkStartColor(new java.awt.Color(225, 0, 225));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        kGradientPanel11.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 390, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/reject(20x20).png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        kGradientPanel11.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, -1));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setOpaque(false);

        table_database.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        table_database.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table_database.setFocusable(false);
        table_database.setGridColor(new java.awt.Color(102, 102, 102));
        table_database.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table_database.setRowHeight(25);
        table_database.setSelectionBackground(new java.awt.Color(153, 153, 255));
        table_database.setSelectionForeground(new java.awt.Color(51, 51, 51));
        table_database.setShowVerticalLines(false);
        table_database.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, sewaPcTableList, table_database);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${harga}"));
        columnBinding.setColumnName("Harga");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${waktu}"));
        columnBinding.setColumnName("Waktu");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nama}"));
        columnBinding.setColumnName("Nama");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${userId}"));
        columnBinding.setColumnName("User Id");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        table_database.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_databaseMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_databaseMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(table_database);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 340));

        kGradientPanel11.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, 340));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("- untuk menghapus data masukan ID usernya aja lalu tekan tombol hapus ");
        kGradientPanel11.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 370, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("- Untuk mengupdate data , pastikan click dulu data yg ingin di updatena");
        kGradientPanel11.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 350, -1));

        getContentPane().add(kGradientPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 520));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        try{
            Connector();
            statSewa = (Statement) connector.createStatement();
            sql = "insert into sewa_pc_table values('"+field_userid.getText()+"','"+field_nama.getText()+"','"+field_waktu.getText()+"','"+field_harga.getText()+"')";
            statSewa.executeUpdate(sql);
            display();
            statSewa.close();
            connector.close();
            Clear();
            JOptionPane.showMessageDialog(null, "berhasil simpan");
            
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
        
        
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        try{
            Connector();
            statSewa = (Statement) connector.createStatement();
            sql = "update sewa_pc_table SET  Nama = '"+field_nama.getText()+"', Waktu = '"+field_waktu.getText()+"', Harga = '"+field_harga.getText()+"' WHERE user_id = '"+field_userid.getText()+"'";
            statSewa.executeUpdate(sql);
            display();
            statSewa.close();
            connector.close();
            Clear();
            JOptionPane.showMessageDialog(null, "berhasil edit");
           
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        Clear();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void field_useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_useridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_useridActionPerformed

    private void field_waktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_waktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_waktuActionPerformed

    private void table_databaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_databaseMouseClicked
        try {
            Connector();
            int row =table_database.getSelectedRow();
            String tabel_klik=(table_database.getModel().getValueAt(row, 0).toString());
            java.sql.Statement stm = connector.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("select * from sewa_pc_table where user_id='"+tabel_klik+"'");
            if(sql.next()){
                String id = sql.getString("user_id");
                field_userid.setText(id);
                String nama = sql.getString("Nama");
                field_nama.setText(nama);
                String waktu = sql.getString("Waktu");
                field_waktu.setText(waktu);
                String harga = sql.getString("Harga");
                field_harga.setText(harga);
            }
        } catch (Exception e) {
//            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_table_databaseMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        try{
            Connector();
            statSewa = (Statement) connector.createStatement();
            sql = "DELETE FROM sewa_pc_table WHERE user_id = '"+field_userid.getText()+"'";
            statSewa.executeUpdate(sql);
            display();
            statSewa.close();
            connector.close();
            JOptionPane.showMessageDialog(null, "berhasil hapus");
           
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        FormSignIn SignIn = new FormSignIn();
        SignIn.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_formMouseDragged

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
      
       try{
       Connector();
       String reportPath = "D:/JAVA/UAS_PBO/SewaPcApp/src/Report/laporan/DAFTAR_SEWAPC.jrxml" ;
       JasperReport jr = JasperCompileManager.compileReport(reportPath);
       JasperPrint jp = JasperFillManager.fillReport(jr,null, connector);
       JasperViewer.viewReport(jp);
       connector.close();
      }catch(Exception e){
          e.printStackTrace();
      }
    }//GEN-LAST:event_kButton1ActionPerformed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        dispose();
    }//GEN-LAST:event_jLabel3MousePressed

    private void table_databaseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_databaseMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_table_databaseMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_simpan;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JTextField field_harga;
    private javax.swing.JTextField field_nama;
    private javax.swing.JTextField field_userid;
    private javax.swing.JTextField field_waktu;
    private javax.swing.JLabel harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel11;
    private javax.swing.JLabel nama;
    private java.util.List<sewapcapp.SewaPcTable> sewaPcTableList;
    private javax.persistence.Query sewaPcTableQuery;
    private javax.swing.JTable table_database;
    private javax.swing.JLabel userid;
    private javax.swing.JLabel waktu;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
